server:
  port: 8888

# spring conf.
spring:
  application:
    name: myblog

  # database conf.
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis conf.
  redis:
    host: localhost
    port: 6379

# mybatis-plus conf.
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    map-underscore-to-camel-case: true # 开启驼峰命名
  global-config:
    db-config:
      table-prefix: ms_

